nombre = input("Escriba su nombre: ")
edad = input("Escriba su edad: ")
altura = input("Escriba su altura: ")
tipo_de_sangre = input("Escriba su tipo de sangre: ")
información = tuple((nombre, edad, altura, tipo_de_sangre))
print(información)

Pais = input("Escriba su pais: ")
ciudad = input("Escriba su ciudad: ")
barrio = input("Escriba su barrio: ")
calle = input("Escriba su calle: ")
carrera= input("Escriba su carrera: ")
direccion = tuple((Pais, ciudad, barrio, calle, carrera))
print(direccion)

titulo_universitario = input("Escriba si tiene titulo universitario o no: ")
donde_estudio = input("Escriba donde ha estudiado: ")
cursos_extra = input("Escriba si ha tomado cursos extra y cuales: ")
maestria = input("Escriba si tiene una maestria: ")
educacion = tuple((titulo_universitario, donde_estudio, cursos_extra, maestria))
print(educacion)

años_experiencia = input("Escriba sus años de experiencia laboral: ")
empresas = input("Escriba las empresas en las que ha trabajado: ")
trabajo_actual = input("Escriba su trabajo actual: ")
aspiracion = input("Escriba sus aspiraciones laborales a futuro: ")
experiancia_laboral = tuple((años_experiencia, empresas, trabajo_actual, aspiracion))
print(experiancia_laboral)